apiVersion: apigeeregistry/v1
kind: API
metadata:
 name: sdlcdemoapi
 labels:
   apihub-business-unit: example
   apihub-lifecycle: develop
   apihub-style: apihub-openapi
   apihub-target-users: public
   apihub-team: example
 annotations:
   apihub-primary-contact: team@example.com
   apihub-primary-contact-description: Dev Team
data:
 displayName: "SDLC Demo API"
 description: "Example API to show the development lifecycle"
 availability: NONE
 versions:
   - metadata:
       name: "0.1.6"
       annotations:
         apihub-end-of-life-date: "2027-09-29T00:00:00.000Z"
         apihub-end-of-life-type: apihub-confirmed
     data:
       displayName: 0.1.6
       state: develop
       specs:
         - metadata:
             name: openapi-016yaml
             annotations:
               apihub-comment: Initial version of YAML       
           data:
             filename: openapi-0.1.6.yaml
             mimeType: "application/x.openapi"
             sourceURI: "file://./openapi.yaml"
         - metadata:
             name: openapi-016json
             annotations:
               apihub-comment: Initial version of JSON        
           data:
             filename: openapi-0.1.6.json
             mimeType: "application/x.openapi"
             sourceURI: "file://./openapi.json"
 deployments:
   - metadata:
       name: mock
       labels:
         apihub-gateway: apihub-unmanaged
       annotations:
         apihub-external-channel-name: ""
     data:
       displayName: mock
       apiSpecRevision: 0.1.6/specs/openapi-016json@latest
       endpointURI: http://35.194.37.184/projects/drush-apigee/locations/global/apis/sdlcdemoapi
       externalChannelURI: ""
       intendedAudience: Currently intended for internal developers only
       accessGuidance: Contact engineering for access to dev